/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.GuestWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author shali
 */
public class GuestWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GuestWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private DB4OUtil dB4OUtil;
    public GuestWorkAreaJPanel(JPanel userProcessContainer, EcoSystem system, DB4OUtil dB4OUtil) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNgoList = new javax.swing.JButton();
        btnRehabList = new javax.swing.JButton();
        btnJobApplication = new javax.swing.JButton();
        btnAgencySignup = new javax.swing.JButton();
        btnRaiseIssue = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        btnNgoList.setText("Trust of EcoSystem");
        btnNgoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrustListActionPerformed(evt);
            }
        });

        btnRehabList.setText("Old Age Home of EcoSystem");
        btnRehabList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOldAgeHomeListActionPerformed(evt);
            }
        });

        btnJobApplication.setText("View Jobs");
        btnJobApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJobApplicationActionPerformed(evt);
            }
        });

        btnAgencySignup.setText("Sign Up as Funding Agency");
        btnAgencySignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgencySignupActionPerformed(evt);
            }
        });

        btnRaiseIssue.setText("Raise Issue");
        btnRaiseIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseIssueActionPerformed(evt);
            }
        });

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Guest Area");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnLogout)
                .addContainerGap(638, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(200, 361, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnNgoList, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRehabList, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnJobApplication, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAgencySignup, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnRaiseIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 162, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogout)
                .addContainerGap(508, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 72, Short.MAX_VALUE)
                    .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(43, 43, 43)
                    .addComponent(btnNgoList)
                    .addGap(31, 31, 31)
                    .addComponent(btnRehabList)
                    .addGap(31, 31, 31)
                    .addComponent(btnJobApplication)
                    .addGap(31, 31, 31)
                    .addComponent(btnAgencySignup)
                    .addGap(31, 31, 31)
                    .addComponent(btnRaiseIssue)
                    .addGap(0, 142, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrustListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrustListActionPerformed
        // TODO add your handling code here:
//        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
//        ViewNGOJPanel vnjp = new ViewNGOJPanel(userProcessContainer, system);
//        userProcessContainer.add("vnjp", vnjp);
//        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnTrustListActionPerformed

    private void btnOldAgeHomeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOldAgeHomeListActionPerformed
        // TODO add your handling code here:
//        CardLayout  cardLayout = (CardLayout) userProcessContainer.getLayout();
//        ViewOldAgeHomeJPanel fghj = new ViewRehabJPanel(userProcessContainer, system);
//        userProcessContainer.add("fghj",fghj);
//        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnOldAgeHomeListActionPerformed

    private void btnJobApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJobApplicationActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        ApplyForJobJPanel afjp = new ApplyForJobJPanel(userProcessContainer, system, dB4OUtil, null, "G");
        userProcessContainer.add("afjp", afjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnJobApplicationActionPerformed

    private void btnAgencySignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgencySignupActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        FundingAgencySignUpJPanel fasujp = new FundingAgencySignUpJPanel(userProcessContainer, system, dB4OUtil);
        userProcessContainer.add("fasujp", fasujp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnAgencySignupActionPerformed

    private void btnRaiseIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseIssueActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        IssueSignUpJPanel isjp = new IssueSignUpJPanel(userProcessContainer, system, dB4OUtil);
        userProcessContainer.add("IssueSignUpJPanel", isjp);
        cardLayout.next(userProcessContainer);
    }//GEN-LAST:event_btnRaiseIssueActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        CardLayout cardLayout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.remove(this);
        cardLayout.previous(userProcessContainer);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgencySignup;
    private javax.swing.JButton btnJobApplication;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNgoList;
    private javax.swing.JButton btnRaiseIssue;
    private javax.swing.JButton btnRehabList;
    private javax.swing.JLabel lblHeader;
    // End of variables declaration//GEN-END:variables
}
